{% set name = "py-mathjax" %}
{% set version = "2.7.5.3" %}
{% set dep_ver = "2.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33a1abaad6c6a09e261aff1769d33b8ff0b4cad03f446680b3df6e9aefa11d9d
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  entry_points:
    - py-mathjax-path = pymathjax.__main__:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mathjax ={{ dep_ver }}

test:
  imports:
    - pymathjax
  commands:
    - py-mathjax-path
    - py-mathjax-path --user

about:
  home: https://github.com/kiwi0fruit/py-mathjax
  license: "Apache 2.0"
  license_family: Apache
  license_file: LICENSE
  summary: "Installs mathjax conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-mathjax
  dev_url: https://github.com/kiwi0fruit/py-mathjax

extra:
  recipe-maintainers:
    - kiwi0fruit
