travis:
  secure:
    BINSTAR_TOKEN: jmn5gK6rlKCVDkpzMZf9XF8ks+VUlAzQLGMTpKVsACmqb/d5v2dwt+rQ0j9krbVPLnmLmDVi+3zrmvTZ0Xt6sUywGIJnOzy0EHhgwSdgXDaGsUbPNlZLQG4VCZ9nAOK95pOT1Vs7BWGprFgEH8xXDtKg4rhjpGZbGyh1g2k53+mtgIolqCe4MZJaPSQ3WsydivORpeaSAFMXWZcerC435mrvnECKsKkOCMNhWjFa2gINwqG+Poi2iQA14UGOeXhjYGMJ9t6J5TS2Mv7K2EGzoxu7BYiD7K7BHj/CiQJv7e1vkel8ol+iq6bnWM1bd/aoy08lb8QfEb1G+Hd4+7UJ50FC+PHTcR6F8A+0X4WbCFSkNwdU6aOjsEAvG+wzUDkPe9mdWI0D1UEmwGBRKU+u3TnWiVntcTaq472FD7bx5j9Im5x3OcK/moXCuTV+zI0puZtoxY7mAXgOsrBhMy2bmWxF9Z7RTOng2x/a8yNgHgHkZHy1sO/UwxsnfdQUyF0/JIMa21kWQyaOKqoKxKVLUgCl1d31OxF4pRdmrXio0Kbf6Zejw3WCLBpxdUX67G/Di/nYgRSLj7VkGRg13vWgGB6I9YUW2UBTTEb6dfWZ6TBg4XF7tu0LovnUneCHQ5GF5Qay5UkVKJcMnrJeLwcqYELSkXMU/gIMXFII0vycnDA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
